nyc_taxi_trip:
  outputs:
    dev:
      dataset: nyc_taxi_trip
      fixed_retries: 1
      keyfile: D:\1--Data Fellowship\Week 5\Weekly Review\nyc_taxi_trip\handy-honor-401601-d115de72ce80.json
      location: us
      method: service-account
      priority: interactive
      project: "handy-honor-401601"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev